import logging
from datetime import datetime
from fpdf import FPDF

logger = logging.getLogger("faceai.pdf_service")

class ProfessionalAttendancePDF(FPDF):
    def header(self):
        # Draw Header Banner Background (Deep Blue: #2563EB)
        self.set_fill_color(37, 99, 235)
        self.rect(0, 0, 210, 40, "F")
        
        # Title text in white
        self.set_text_color(255, 255, 255)
        self.set_font("helvetica", "B", 18)
        self.cell(0, 12, "Face AI Attendance System", ln=True, align="C")
        self.set_font("helvetica", "B", 12)
        self.cell(0, 5, "Attendance Report", ln=True, align="C")
        self.ln(12)
        
        # Reset color
        self.set_text_color(0, 0, 0)

    def footer(self):
        self.set_y(-15)
        self.set_font("helvetica", "I", 8)
        self.set_text_color(156, 163, 175)  # gray text
        self.cell(0, 10, f"Generated by Face AI Attendance System  |  Page {self.page_no()}", align="C")

def build_pdf_report(records: list[dict], date_range_str: str) -> bytes:
    """
    Generate a professional enterprise-grade PDF file from filtered attendance records.
    """
    try:
        total_users = len({r.get("user_id") for r in records})
        present = sum(1 for r in records if r.get("attendance_status") == "Present")
        absent = sum(1 for r in records if r.get("attendance_status") == "Absent")
        late = sum(1 for r in records if r.get("attendance_status") == "Late")
        half_day = sum(1 for r in records if r.get("attendance_status") == "Half Day")

        pdf = ProfessionalAttendancePDF()
        pdf.set_auto_page_break(auto=True, margin=20)
        pdf.add_page()
        pdf.ln(15)

        pdf.set_font("helvetica", "B", 12)
        pdf.set_text_color(31, 41, 55)
        pdf.cell(0, 10, f"Selected Date Range: {date_range_str}", ln=True)
        pdf.ln(2)

        pdf.set_font("helvetica", "B", 10)

        pdf.set_fill_color(243, 244, 246)
        pdf.set_text_color(31, 41, 55)
        pdf.cell(38, 12, f"Total Users: {total_users}", border=1, fill=True, align="C")

        pdf.set_fill_color(209, 250, 229)
        pdf.set_text_color(6, 95, 70)
        pdf.cell(38, 12, f"Present: {present}", border=1, fill=True, align="C")

        pdf.set_fill_color(254, 226, 226)
        pdf.set_text_color(153, 27, 27)
        pdf.cell(38, 12, f"Absent: {absent}", border=1, fill=True, align="C")

        pdf.set_fill_color(254, 243, 199)
        pdf.set_text_color(146, 64, 14)
        pdf.cell(38, 12, f"Late: {late}", border=1, fill=True, align="C")

        pdf.set_fill_color(219, 234, 254)
        pdf.set_text_color(30, 58, 138)
        pdf.cell(38, 12, f"Half Day: {half_day}", border=1, fill=True, align="C", ln=True)

        pdf.ln(8)

        pdf.set_text_color(31, 41, 55)
        pdf.set_font("helvetica", "B", 12)
        pdf.cell(0, 8, "Detailed Records List", ln=True)
        pdf.ln(2)

        col_w = [18, 32, 42, 22, 30, 30, 16]
        headers = ["Emp ID", "Name", "Email", "Status", "Check-In", "Check-Out", "Hours"]

        pdf.set_font("helvetica", "B", 9)
        pdf.set_fill_color(37, 99, 235)
        pdf.set_text_color(255, 255, 255)

        for w, header in zip(col_w, headers):
            pdf.cell(w, 8, str(header), border=1, fill=True, align="C")
        pdf.ln()

        pdf.set_font("helvetica", "", 8)
        pdf.set_text_color(0, 0, 0)

        for idx, r in enumerate(records, 1):
            fill = idx % 2 == 0
            if fill:
                pdf.set_fill_color(249, 250, 251)

            in_str = str(r.get("check_in_time", "-") or "-")
            if in_str != "-":
                try:
                    in_str = datetime.strptime(in_str, "%Y-%m-%d %H:%M:%S").strftime("%m-%d %H:%M")
                except Exception:
                    pass

            out_str = str(r.get("check_out_time", "-") or "-")
            if out_str != "-":
                try:
                    out_str = datetime.strptime(out_str, "%Y-%m-%d %H:%M:%S").strftime("%m-%d %H:%M")
                except Exception:
                    pass

            working_hours = r.get("working_hours", 0) or 0

            row_data = [
                str(r.get("employee_id", "")),
                str(r.get("name", ""))[:18],
                str(r.get("email", ""))[:25],
                str(r.get("attendance_status", "")),
                in_str,
                out_str,
                f"{float(working_hours):.1f}",
            ]

            for w, val in zip(col_w, row_data):
                pdf.cell(w, 7, val, border=1, fill=fill, align="C")
            pdf.ln()

        pdf_output = pdf.output(dest="S")

        if isinstance(pdf_output, bytearray):
            pdf_bytes = bytes(pdf_output)
        elif isinstance(pdf_output, bytes):
            pdf_bytes = pdf_output
        elif isinstance(pdf_output, str):
            pdf_bytes = pdf_output.encode("latin-1", errors="replace")
        else:
            pdf_bytes = bytes(pdf_output)

        if not pdf_bytes.startswith(b"%PDF"):
            raise ValueError("Generated file is not a valid PDF.")

        return pdf_bytes

    except Exception as e:
        logger.exception(f"Failed to build PDF report: {e}")
        raise